### ISSUE TITLE
ProteoRE: Web server issue guidelines from NAR

### ISSUE THREAD

**Issue by yvandenb** [vloux/ProteoRE#156]
As a reminder & to be further discussed once the V 1.2 released
The WEB SERVER MUST:

BE FUNCTIONAL on the date of the proposal submission. Access to the server must be through a web browser. Note that authors are encouraged to use HTTPS protocol and are required to do so if the website accepts or transmits sensitive data (such as confidential personal information or protected health information). HTTPS protocol will be required for all websites in the future. Non-server application programs will only be considered for high-throughput data (see above).
include a simple mechanism to try out sample data provided by the authors, for example, a button for automatic loading of the data. Sample data must be accessible to users so that they can confirm data formatting requirements.
contain help pages or a tutorial with links to sample output that performs interactively in the same way as real output. The help pages must include information on how to interpret the results returned by the web server. Authors are encouraged to add a summary of their website's browser compatibility on the help page, in a table format such as the following:
Browser compatibility
Please READ: https://academic.oup.com/nar/pages/Submission_Webserver

**Comment by yvandenb** [comment]
To be read, to comply with 
https://academic.oup.com/nar/pages/Submission_Webserver

**Comment by yvandenb** [comment]
how to create SSL certificate via GANDI : https://docs.gandi.net/fr/ssl/creation/index.html

**Comment by vloux** [comment]
GANDI's solution is'nt free if you don't use their hosting solution.
I used lets'encrypt solution with their `certbot`tool.
Followed instrcutions there : https://certbot.eff.org/lets-encrypt/centosrhel7-apache
Done in a few minutes.

https://proteore.org is valid and running.

<img width="474" alt="Capture d’écran 2021-07-22 à 11 46 33" src="https://user-images.githubusercontent.com/477640/126620161-cea9bb1d-319b-4e74-9180-ad5d350a7e17.png">

**Comment by yvandenb** [comment]
Génial !! Merci Valentin 👍
