### ISSUE TITLE
Release ProteoR V2.1 : todo list

### ISSUE THREAD

**Issue by yvandenb** [vloux/ProteoRE#270]
In the following order (to be discussed):
1. Data manager et HPA data sources : see issue #269 (David)
2. ID Converter (Human, Mouse, Rat) : to be updated on proteore.org (David)
3. Add protein features (3 orga) [UniProt] : to be deployed on proteore.org (Flo)
4. "GO terms enrich comparison" à revoir userDoc (Flo bascule sur GitHub , Yves modifie le xml) 
https://github.com/ifb-git/ProteoRE/blob/master/tools/GO_terms_enrich_comparison/GO_terms_enrich_comparison.xml
5. Menu du tool panel à mettre à jour voir #267 (Flo)
6. files to be updated and carefully verified (all): fiare via le *github puis copier dans le serveur (static directory)
https://github.com/ifb-git/ProteoRE/blob/master/static/data_source.html (Flo/David) 
http://www.proteore.org/u/proteore/p/proteore-previous-release-notes (via Git or shared page via proteore admin:  unable to find it ?) => https://github.com/ifb-git/ProteoRE/blob/master/static/proteore_previous_releases_notes.html
https://github.com/ifb-git/ProteoRE/blob/master/static/communication.html (done by YV)
7. home page (via GitHub or via admin interface?) to be fully updated (YV) => creation of  
https://github.com/ifb-git/ProteoRE/blob/master/static/welcome_2.1.html
8. Tutorial and workflow to be tested/updated/verified and GTN as well (last task)

**Comment by combesf** [comment]
4. : done
3. : will be done when I'll do 5.

So : what is the status for 1. and 2. ?

**Comment by davidchristiany** [comment]
Fot 1 and 2, hopefully it will be done by the end of the day :)

**Comment by combesf** [comment]
just let me know once done, it will be perfect !
Thanks David.

**Comment by davidchristiany** [comment]
Done

**Comment by yvandenb** [comment]
May be I missed sthg, but updated version of "Build tissue-specific expression dataset" (Version 2019.06.27) and "Add expression data" (Galaxy Version 2019.06.27) (as discussed this morning by David and I) are missing on proteore.org...aren't they, David ?

**Comment by combesf** [comment]
The tool 
"proteore_get_unique_peptide_srm_method" 
is not on the GitHub (?) so I cannot update it on proteore.org

**Comment by yvandenb** [comment]
yet this tool has been deposited in the toolShed https://toolshed.g2.bx.psu.edu/view/proteore/proteore_get_unique_peptide_srm_method/a2b06836de90

**Comment by combesf** [comment]
yes, but the text in the tool panel for this tool has to be modified in the new proteore version, 
so I have to access the code files of the tool.

**Comment by combesf** [comment]
as far as I know, I cannot access the code files via the TS. 
@davidchristiany  can you deposit the code on th GitHub please in a directiry, as for the other tools ? 
Thanks !

**Comment by davidchristiany** [comment]
This tool is not on github, I don't know why, it is weird.
I am working at home right now so I don't have my main computer, but if it is not on github I don't have it. 

I will investigate but in the worst case scenario, we can download it from toolshed:
https://toolshed.g2.bx.psu.edu/repository/download?repository_id=21b93c7fadbdb478&changeset_revision=a2b06836de90&file_type=gz 
and push it on github.

Did we change the name of this tool ?

**Comment by yvandenb** [comment]
>Did we change the name of this tool ?
From the wiki : https://github.com/ifb-git/ProteoRE/wiki/V2.1-tools-name-equivalence
Get unique peptide SRM-MRM method [SRM Atlas] --> Get unique peptide SRM-MRM method [Human SRM Atlas]

**Comment by davidchristiany** [comment]
I added it on github from the toolshed

**Comment by combesf** [comment]
I have versy strange behavior for some of the tools (tool with reactome for ex., but it concerns more than 3 tools): 
The new version is on the toolshed, date from 23d or 24th of January
on the admin page of the proteore instance, galaxy does not find this new version, and so it is not possible to update the tool. 

But for some tools, all is OK. it is very strange.

**Comment by davidchristiany** [comment]
Usually when a tool version is not available to download, it means there is a problem with that version so Galaxy won't let you install it. It is often a small error like a missing tag or a missing ")".
It may be the case here

**Comment by davidchristiany** [comment]
it's not the case for "athway enrichment analysis" (reactome), I just installed it on proteore-migale from the main toolshed.

**Comment by combesf** [comment]
I reorganized the "integrated_tool_panel.xml" , renaming the sections and reorganizing the tools, and then restarted the instance. 
All is a mess ... 
So I made modifications in the config/shed_tool_conf.xml file, and then restarted ... and it is also the mess. 

In order not to loose too much time: could you please tell me which file to modify first : 
shed_tool_conf.xml ?
integrated_tool_panel.xml ?
other file ? 

Thanks

**Comment by davidchristiany** [comment]
I don't think you need to modify the shed_tool_conf.xml file. It should be fine just with the reogranisation of the integrated_tool_panel.

**Comment by combesf** [comment]
But it is no fine. For example 

I suppress a tool from integrated_tool_panel, suppressing this line:
<tool id="toolshed.g2.bx.psu.edu/repos/proteore/proteore_prot_features_mouse/prot_features_mouse/2019.06.27" />

When I restart proteore instance, the line is there again ... 

and the lines are mixed between the section.

**Comment by combesf** [comment]
also : 
I replace the line <label id="human_annotation" text="Human Annotation" version="" />
by 
<label id="get_features_experimental_data" text="Get Features/Experimental Data" version="" />

and after the restart, 
the 1st line is back again

**Comment by combesf** [comment]
I finally managed to order the tool panel correctly. 
BUT impossible to change the name of the subsection (when I try, it mixes all the tools between the section ....): ???
I decided to let "as is" for today. 

I saved the "integrated_tool_panel.xml" in a version : "integrated_tool_panel.xml.flo20200124" to be sure not to erase it while restarting. 

CAREFUL: the mainToolShed is up to date, but NOT the ifb GitHub. 
I'll do this next week. If needed tell me.

**Comment by yvandenb** [comment]
- [ ] the following static html page have been updated:
https://github.com/ifb-git/ProteoRE/blob/master/static/proteore_previous_releases_notes.html
https://github.com/ifb-git/ProteoRE/blob/master/static/communication.html 
https://github.com/ifb-git/ProteoRE/blob/master/static/welcome_2.1.html
Please could someone deployed them on migale-proteore, so that we can all verified beforehand
- [ ] David/Flo/Val: don't forget to update: https://github.com/ifb-git/ProteoRE/blob/master/static/data_source.html

**Comment by yvandenb** [comment]
>Please could someone deployed them on migale-proteore, so that we can all verified beforehand ?
As a reminder: Please can someone update the html pages so that we could verify ?

**Comment by combesf** [comment]
> CAREFUL: the mainToolShed is up to date, but NOT the ifb GitHub.
> I'll do this next week. If needed tell me.

The ifb ProteoRE GitHub is now up-to-date

**Comment by combesf** [comment]
> > Please could someone deployed them on migale-proteore, so that we can all verified beforehand ?
> > As a reminder: Please can someone update the html pages so that we could verify ?

I do this.

**Comment by yvandenb** [comment]
OK, let me know once done ;-)

**Comment by combesf** [comment]
Done. 
I put the 3 html files on proteore2/galaxy/static
(I did like in the #220 ticket ; hope it is OK)

**Comment by davidchristiany** [comment]
I fixed the welcome page and html pages on proteore-migale (html link are different from github because github static html pages are meant to be on proteore.org and not proteore-migale).

**Comment by yvandenb** [comment]
Hi fellows, 
I updated the following static files:
https://github.com/ifb-git/ProteoRE/blob/master/static/proteore_previous_releases_notes.html
https://github.com/ifb-git/ProteoRE/blob/master/static/communication.html
https://github.com/ifb-git/ProteoRE/blob/master/static/welcome_2.1.html
https://github.com/ifb-git/ProteoRE/blob/master/static/data_source.html
Should now be verified, please David could you deployed them one more time for final check

**Comment by davidchristiany** [comment]
Done

**Comment by yvandenb** [comment]
Todo list remaining tasks : 
1. Tool « Build tissue-specific expression dataset” en cours de finalization par David cf issue #272 
2.	Tool “Volcano-plot”: identification d’un bug dû à un package obsolete => assigned to VL  cf  issue #273   
3.	Placer les pages static html updatées du GitHub sous proteore-Migale (Flo peux-tu t’en charger, stp ?)
4.	Une fois que tout cela est fait-vérifié-validé => placer une banner d’interruption de service sur le site de prod la veille du déploiement  
5.	Faire le deploiement + update workflow « biomarkers cancer » + tests random + check "whiteList" (Jvenn, HeatMap, Reactome)
6.	Training materials Update des workflow et check hands-on GTN 
7.	Remettre en service + Envoi de l’announcement

**Comment by davidchristiany** [comment]
@yvandenb can you tell me if Build tissue specific dataset is ok on proteore-migale ? 
It will be exactly the same on proteore.org.

**Comment by yvandenb** [comment]
I've just tested this tool, works fine; btw the solution to overcome the problem of two different list of tissues you implemented is just fine ! :-)

**Comment by yvandenb** [comment]
2.1 now released...
Last task: Training materials Update des workflow et check hands-on GTN (Flo)
