### ISSUE TITLE
Update GO databases for goProfile, ClusterProfiler, ClusterComparison, TopGo tools

### ISSUE THREAD

**Issue by yvandenb** [vloux/ProteoRE#290]
En vue de la prochaine relase ProteoRE, mise à joiur des GO.db pour Human (Hs), Mouse (Mm)  and Rat (Rn) merci

**Comment by vloux** [comment]
- [x] goProfile #292
- [ ]  ClusterProfiler
- [ ] ClusterComparison
- [ ] TopGo

**Comment by yvandenb** [comment]
Cluster profiler tested in http://migale.jouy.inra.fr/proteore -> everything OK :-)

**Comment by yvandenb** [comment]
@vloux please could you indicate the release number of each GO db you updated (I need it to pudate the "data_source.html" page: 
- bioconductor-org.hs.eg.db v?.?.?
- bioconductor-org.mm.eg.db v?.?.?
- bioconductor-org.rn.eg.db v?.?.?

**Comment by yvandenb** [comment]
OK
