### ISSUE TITLE
Proteore.org tool panel to be updated

### ISSUE THREAD

**Issue by yvandenb** [vloux/ProteoRE#313]
Merci de replacer les outils "Venn diagram [JVenn]", "Get unique peptide SRM-MRM method [Human SRM Atlas]" et "Pathway enrichment analysis [Reactome]" dans les bonnes sections comme indiqué dans le snap ci-dessous ci-dessous : 

![image](https://user-images.githubusercontent.com/29478729/120347248-66f7e000-c2fc-11eb-8161-3ccab5091e94.png)

PS: penser à retirer la banner de maintenance ;-)

**Comment by yvandenb** [comment]
Proteore.org now updated...check with Flo once the update of 'Add Protein Features Uniprot' done; Then please reorganize the tool panel as shown above and replace the current welcome html page by this one : https://github.com/vloux/ProteoRE/blob/master/static/Welcome_Page_3.0.html

**Comment by vloux** [comment]
Done !

**Comment by yvandenb** [comment]
static html pages updated and to be replaced: 
https://github.com/vloux/ProteoRE/blob/master/static/communication.html
https://github.com/vloux/ProteoRE/blob/master/static/proteore_previous_releases_notes.html
https://github.com/vloux/ProteoRE/blob/master/static/data_source.html
then replace the right welcome page: https://github.com/vloux/ProteoRE/blob/master/static/Welcome_Page_3.0.html

**Comment by vloux** [comment]
Done
